wrk: some path
boom: some path
pliny: some url
gin: some url

bench:
  duration: 1m
  requests: 100000
  connections:
    - 50
    - 100
    - 150
    - 200
    - 250
    - 500
    - 1000
    - 1500
    - 2000
    - 2500
    - 5000
    - 10000
